version: '3.3'

services:
    # image project
    ceilr:
        build:
            args:
                user: ceilr
                uid: 1000
            context: ./docker/php/
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - ceilr_network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - '${DB_APP_PORT:-80}:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - ceilr_network

    # db mysql
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_USER: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
            - './docker/create_testing_db.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        ports:
            - '${DB_FORWARD_PORT:-3306}:3306'
        networks:
            - ceilr_network

networks:
    ceilr_network:
        driver: bridge